### ISSUE TITLE
Running with application default credentials in Kubernetes "Error: Required parameter: project"

### ISSUE THREAD

**Issue by stfl** [Lith/strapi-plugin-analytics#1]
I deploy to GKE through Gitlab. I used the minimal configuration with only providing the bucket name.
I get the following error:

```
2021-03-04T14:21:24.071406416Z
[2021-03-04T14:21:24.070Z] error Error: Required parameter: project at new ApiError (/strapi/node_modules/@google-cloud/common/build/src/util.js:59:15) at Util.parseHttpRespBody (/strapi/node_modules/@google-cloud/common/build/src/util.js:194:38) at Util.handleResp (/strapi/node_modules/@google-cloud/common/build/src/util.js:135:117) at /strapi/node_modules/@google-cloud/common/build/src/util.js:434:22 at onResponse (/strapi/node_modules/retry-request/index.js:214:7) at /strapi/node_modules/teeny-request/build/src/index.js:219:13 at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by stfl** [comment]
sorry. wrong repo
